name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./project

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: ${{env.working-directory}}
    - name: driver1
      run: ./driver1
      working-directory: ${{env.working-directory}}
    - name: driver2
      run: ./driver2
      working-directory: ${{env.working-directory}}
    - name: driver3
      run: ./driver3
      working-directory: ${{env.working-directory}}
    - name: driver4
      run: ./driver4
      working-directory: ${{env.working-directory}}
    - name: driver5
      run: ./driver5
      working-directory: ${{env.working-directory}}
    - name: driver6
      run: ./driver6
      working-directory: ${{env.working-directory}}
